# Generated by Django 2.2.1 on 2019-06-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(default='', verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='课程机构名称'),
        ),
    ]
